### PR TITLE
Remove link to Red Cross donation

### PR DESCRIPTION
**Pull request by Pernat1y**
Removed Red Cross donation link, as they spending money in a terrible way.
Sources:
https://mobile.twitter.com/your_psychoo/status/1507110118906863617?s=21&t=8Wz67Xfp19a3lT6r0VaIwg
https://life.pravda.com.ua/society/2022/03/26/247987/
https://telegraf.com.ua/ukr/ukraina/2022-03-25/5700516-na-krasnom-kreste-mozhno-stavit-krest-ukraintsev-vozmutili-strannye-dogovorennosti-s-lavrovym
https://nv.ua/ukr/ukraine/events/chervoniy-hrest-skandal-z-ofisom-u-rostovi-nacionalniy-komitet-poyasniv-situaciyu-novini-ukrajini-50228742.html

If you want to support Ukraine (which is great), use different donation method - The Return Alive Foundation ( https://savelife.in.ua/en/donate/ or https://www.comebackalive.in.ua/donate ), for example.

### CODE REVIEW

**Comment by TheFrenchGhosty** [comment]
I won't change it.

The Red Cross is a well known charity, that's focused on helping civilians while being roughly apolitical.

Both the associations you linked are highly political and focus on helping the army.

I'm not interested in recommending associations focused on helping people kill each others.

**Comment by Pernat1y** [comment]
Being a "well known charity" does not mean to be effective or, in this particular situation, useful at all.
They spending donation money to build infrastructure on the territory of an aggressive country (AKA Russia), which is totally inappropriate.
Anyway, that's still for you to decide, whom to support.

**Comment by TheFrenchGhosty** [comment]
> They spending donation money to build infrastructure on the territory of an aggressive country (AKA Russia), which is totally inappropriate.

There's civilians on both side.

**Comment by Pernat1y** [comment]
> > They spending donation money to build infrastructure on the territory of an aggressive country (AKA Russia), which is totally inappropriate.
> 
> There's civilians on both side.
>

True. But at this particular moment, the situation in Ukraine is much more critical and urgent. Civilians there are being attacked, killed, forced to leave their property without knowing if they even are being able to return, as cities are being flattened by bombardments and artillery.

**Comment by TheFrenchGhosty** [comment]
@Pernat1y I don't do politics, nor take a side publicly.

**Comment by Pernat1y** [comment]
> @Pernat1y I don't do politics, nor take a side publicly.

Same. Then my country was invaded.
Don't see any point in further discussion, so I am out.

**Pull request closed without merging**
